"""initial schema

Revision ID: 4ebfcff544f5
Revises:
Create Date: 2026-06-10 23:14:20.607617

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4ebfcff544f5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "acts",
        sa.Column("act_ref", sa.Text(), nullable=False),
        sa.Column("act_type", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("collection", sa.Text(), nullable=False),
        sa.Column("vigenza", sa.Text(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("last_commit_sha", sa.Text(), nullable=True),
        sa.Column("last_updated", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("number", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("date_pub", sa.Date(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "vigenza IN ('vigente', 'abrogato', 'decaduto')", name="ck_acts_vigenza"
        ),
        sa.PrimaryKeyConstraint("act_ref"),
    )
    op.create_index("ix_acts_collection", "acts", ["collection"], unique=False)
    op.create_index("ix_acts_vigenza", "acts", ["vigenza"], unique=False)
    op.create_table(
        "ingestion_progress",
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("commit_sha", sa.Text(), nullable=False),
        sa.Column("act_ref", sa.Text(), nullable=True),
        sa.Column("indexed_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("file_path"),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("finished_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("kind", sa.Text(), nullable=True),
        sa.Column("commit_from", sa.Text(), nullable=True),
        sa.Column("commit_to", sa.Text(), nullable=True),
        sa.Column("files_processed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("files_skipped", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "errors",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), nullable=True),
        sa.CheckConstraint("kind IN ('bootstrap', 'delta')", name="ck_ingestion_runs_kind"),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed')", name="ck_ingestion_runs_status"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ingestion_runs")
    op.drop_table("ingestion_progress")
    op.drop_index("ix_acts_vigenza", table_name="acts")
    op.drop_index("ix_acts_collection", table_name="acts")
    op.drop_table("acts")
    # ### end Alembic commands ###
